name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build
        run: |
          sudo apt-get install build-essential automake pkg-config libtool libffi-dev libssl-dev libgmp-dev python3-dev
      # - name: Lint with Rubocop
      #   run: |
      #     bin/rubocop
      - name: Test
        run: |
          rake test
