name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Lint with Rubocop
        run: bin/rubocop
      # - name: Build and run tests
      #   run: |
      #     sudo apt-get -yqq install libpq-dev
      #     gem install bundler
      #     bundle install --jobs 4 --retry 3
      #     bundle exec rake spec
